### PR TITLE
Fixed DNS missing subdomain, removed regions, moved to root

### PR DESCRIPTION
**Pull request by botzill**

### CODE REVIEW

**Comment by styk-tv** [comment]
Please add parameter files to .gitignore
Missing subdomain is required why? We should not have "madcore" subdomain. Need to find out why its needed. It can probably be substituted with something we already have in the pool.

**Comment by botzill** [comment]
I'm not sure why we need that subdomain, but according to this it was required 

https://github.com/madcore-ai/core/blob/master/bin/redis_add_basic_apps.py#L6

Maybe we can deleted it from there and we can as well delete from CF.

**Comment by styk-tv** [comment]
yes. it can be removed. this is why it was excluded from cf

**Comment by botzill** [comment]
Done, subdomain removed.

**Pull request merged**
